# Generated by Django 3.0.8 on 2020-08-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lagou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50)),
                ('edu', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('compensation', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Liepin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50)),
                ('edu', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('compensation', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
